name: Despliegue - EcomerBack
 
on:
  push:
    branches:
      - main
 
jobs:
  # --- TRABAJO 1: CONSTRUIR LA APLICACIÓN ---
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
 
      - name: Configurar Node.js y pnpm con caché
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Asegúrate que coincida con la de tu servidor
          cache: 'pnpm'
 
      - name: Instalar dependencias
        run: pnpm install
 
      - name: Construir la aplicación
        run: pnpm run build
 
      - name: Preparar paquete de despliegue
        run: |
          mkdir deploy_package
          cp -r dist deploy_package/
          cp package.json pnpm-lock.yaml pm2.config.js deploy_package/
 
      - name: Instalar solo dependencias de producción
        run: |
          cd deploy_package
          sudo pnpm install 
 
      - name: Crear archivo .env.prod en el paquete
        run: |
          cd deploy_package
          echo "ECOMER_DB_TYPE=${{ secrets.ECOMER_DB_TYPE }}" > .env.prod
          echo "ECOMER_DB_HOST=${{ secrets.ECOMER_DB_HOST }}" >> .env.prod
          echo "ECOMER_DB_PORT=${{ secrets.ECOMER_DB_PORT }}" >> .env.prod
          echo "ECOMER_DB_USERNAME=${{ secrets.ECOMER_DB_USERNAME }}" >> .env.prod
          echo "ECOMER_DB_PASSWORD=${{ secrets.ECOMER_DB_PASSWORD }}" >> .env.prod
          echo "ECOMER_DB_DATABASE=${{ secrets.ECOMER_DB_DATABASE }}" >> .env.prod
          echo "ECOMER_PORT=${{ secrets.ECOMER_PORT }}" >> .env.prod
          echo "ECOMER_API_SAMBOX=${{ secrets.ECOMER_API_SAMBOX }}" >> .env.prod
          echo "ECOMER_PUBLI=${{ secrets.ECOMER_PUBLI }}" >> .env.prod
          echo "ECOMER_PRIVATE=${{ secrets.ECOMER_PRIVATE }}" >> .env.prod
          echo "ECOMER_EVENT=${{ secrets.ECOMER_EVENT }}" >> .env.prod
          echo "ECOMER_INTEGRIDAD=${{ secrets.ECOMER_INTEGRIDAD }}" >> .env.prod
          
      - name: Comprimir artefacto para despliegue
        run: |
          cd deploy_package
          tar -czf ../ecomerce-back.tar.gz .
 
      - name: Subir artefacto para el trabajo de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: ecomerce-back.tar.gz
 
  # --- TRABAJO 2: DESPLEGAR EN EL SERVIDOR ---
  deploy:
    runs-on: ubuntu-latest
    needs: build # Este trabajo depende de que 'build' termine correctamente
    steps:
      - name: Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
 
      - name: Copiar paquete al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "ecomerce-back.tar.gz"
          target: "/home/proyet"
 
      - name: Desplegar y reiniciar en el servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e # Terminar el script si algún comando falla
 
            # Definir directorios
            APP_DIR="/home/proyet/ecomerce-back"
            BACKUP_DIR="/home/proyet/versions/ecomerce-back"-$(date +%Y%m%d%H%M%S)"
            
            # 1. Crear backup de la versión anterior (si existe)
            if [ -d "$APP_DIR" ]; then
              echo "INFO: Realizando backup de la versión actual en $BACKUP_DIR"
              sudo mv "$APP_DIR" "$BACKUP_DIR"
            fi
            
            # 2. Crear el directorio de la nueva aplicación y descomprimir
            echo "INFO: Creando nuevo directorio y descomprimiendo..."
            sudo mkdir -p "$APP_DIR"
            sudo tar -xzf "/home/proyet/ecomerce-back.tar.gz" -C "$APP_DIR"
            sudo rm "/home/proyet/ecomerce-back.tar.gz"
 
            # 3. Reiniciar el servicio con PM2
            echo "INFO: Recargando la aplicación con PM2..."
            cd "$APP_DIR"
            # Intenta recargar la app; si no existe, la inicia.
            # Asegúrate que 'pm2.config.js' esté configurado para usar sudo si es necesario.
            sudo pm2 reload pm2.config.js || sudo pm2 start pm2.config.js
            sudo pm2 save
            
            echo "✅ Despliegue completado."
