name: Despliegue - EcomerBack
 
on:
  push:
    branches:
      - main
 
jobs:
  # --- TRABAJO 1: CONSTRUIR LA APLICACIÓN ---
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        run: npm install -g pnpm
 
      - name: Configurar Node.js y pnpm con caché
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Asegúrate que coincida con la de tu servidor
          cache: 'pnpm'

      - name: Crear archivo .env.prod en el paquete
        run: |
          touch .env.prod 
          echo "ECOMER_DB_TYPE=${{ secrets.ECOMER_DB_TYPE }}" >> .env.prod
          echo "ECOMER_DB_HOST=${{ secrets.ECOMER_DB_HOST }}" >> .env.prod
          echo "ECOMER_DB_PORT=${{ secrets.ECOMER_DB_PORT }}" >> .env.prod
          echo "ECOMER_DB_USERNAME=${{ secrets.ECOMER_DB_USERNAME }}" >> .env.prod
          echo "ECOMER_DB_PASSWORD=${{ secrets.ECOMER_DB_PASSWORD }}" >> .env.prod
          echo "ECOMER_DB_DATABASE=${{ secrets.ECOMER_DB_DATABASE }}" >> .env.prod
          echo "ECOMER_PORT=${{ secrets.ECOMER_PORT }}" >> .env.prod
          echo "ECOMER_API_SAMBOX=${{ secrets.ECOMER_API_SAMBOX }}" >> .env.prod
          echo "ECOMER_PUBLI=${{ secrets.ECOMER_PUBLI }}" >> .env.prod
          echo "ECOMER_PRIVATE=${{ secrets.ECOMER_PRIVATE }}" >> .env.prod
          echo "ECOMER_EVENT=${{ secrets.ECOMER_EVENT }}" >> .env.prod
          echo "ECOMER_INTEGRIDAD=${{ secrets.ECOMER_INTEGRIDAD }}" >> .env.prod
 
      - name: Instalar dependencias
        run: pnpm install
 
      - name: Construir la aplicación
        run: pnpm run build
          
      - name: Comprimir artefacto para despliegue
        run: |
          cd ../
          tar -czf ecomerce-back.tar.gz ./ecomerce-back

      - name: copiar archivo contruido
        run: |
          cd ../
          cp ecomerce-back.tar.gz ./ecomerce-back
 
      - name: Subir artefacto para el trabajo de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: ecomerce-back.tar.gz
 
  # --- TRABAJO 2: DESPLEGAR EN EL SERVIDOR ---
  deploy:
    runs-on: ubuntu-latest
    needs: build # Este trabajo depende de que 'build' termine correctamente
    steps:
      - name: Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
 
      - name: Copiar paquete al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "ecomerce-back.tar.gz"
          target: "/home/proyet"
 
      - name: Desplegar y reiniciar en el servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e # Terminar el script si algún comando falla
            
            # 1. Crear el directorio de la nueva aplicación y descomprimir
            echo "INFO: Creando nuevo directorio y descomprimiendo..."
            sudo rm -rf /home/proyet/ecomerce-back
            mkdir /home/proyet/ecomerce-back
            tar -xzf /home/proyet/ecomerce-back.tar.gz -C /home/proyet/ecomerce-back
            sudo rm -rf /home/proyet/ecomerce-back.tar.gz
            
      - name: Levantar pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
           # 2. Reiniciar el servicio con PM2
             echo "INFO: Recargando la aplicación con PM2..."
             cd /home/proyet/ecomerce-back
             # Intenta recargar la app; si no existe, la inicia.
             # Asegúrate que 'pm2.config.js' esté configurado para usar sudo si es necesario.
             pm2 reload pm2.config.js || pm2 start pm2.config.js
             pm2 save
             
             echo "✅ Despliegue completado."
